# docs: https://rust-lang.github.io/mdBook
[book]
title = "mcpp-standard项目 | 现代C++核心语言特性代码练习"
author = "sunrispeak"
language = "zh"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/Sunrisepeak/mcpp-standard"

[preprocessor.foo]
# Add any additional configurations
